In [15]:
import numpy as np
#que 1 
a = np.array([1,2,3,4,5,6])
print(a.reshape(2,3))


[[1 2 3]
 [4 5 6]]


In [43]:
#que 2 
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a [ a==b]

array([2, 2, 4, 4])

In [49]:
#que 3
a = np.array([2, 6, 1, 9, 10, 3, 27]) 
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

In [ ]:
#que 4


In [73]:
#que 5
import pandas as pd
data = pd.Series([1,2,3,4,5])
data.min()
data.quantile(0.25)
data.median()
data.quantile(0.75)
data.max()

5

In [77]:
#que 2
import pandas as pd

data = ({
    'Name':['Jack','Jack','Alice'],
    'Age':[20,21,22]}
       )
df = pd.DataFrame(data)

print(df)

    Name  Age
0   Jack   20
1   Jack   21
2  Alice   22


In [81]:
#que 3
data = np.random.randint(1,100,(5,3))
df = pd.DataFrame(data)
df

,0,1,2
0,70,45,34
1,27,67,74
2,64,22,75
3,52,21,19
4,89,79,72


In [ ]:
# que 5
df = pd.read_csv("Matches.csv")